### ISSUE TITLE
training in Colab A100 vs V100

### ISSUE THREAD

**Issue by fred-dev** [Stability-AI/stable-audio-tools#35]
Hi, I am trying to train using google colab, it works fine with a V100, but if I get an A100 I cannot run train.py

I get this output (the exact same settings work fine for V100 and I tried using 16-mixed and bf16-mixed: 

```
You are using a CUDA device ('NVIDIA A100-SXM4-40GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name          | Type                  | Params
--------------------------------------------------------
0 | diffusion     | DiffusionModelWrapper | 221 M 
1 | diffusion_ema | EMA                   | 442 M 
2 | losses        | MultiLoss             | 0     
--------------------------------------------------------
221 M     Trainable params
221 M     Non-trainable params
442 M     Total params
1,771.115 Total estimated model params size (MB)
Epoch 0:   0% 0/128 [00:00<?, ?it/s] /content/stable-audio-tools/stable_audio_tools/models/blocks.py:68: UserWarning: Memory efficient kernel not used because: (Triggered internally at ../aten/src/ATen/native/transformers/cuda/sdp_utils.cpp:415.)
  y = F.scaled_dot_product_attention(q, k, v, is_causal=False).contiguous().view([n, c, s])
/content/stable-audio-tools/stable_audio_tools/models/blocks.py:68: UserWarning: Memory Efficient attention has been runtime disabled. (Triggered internally at ../aten/src/ATen/native/transformers/sdp_utils_cpp.h:456.)
  y = F.scaled_dot_product_attention(q, k, v, is_causal=False).contiguous().view([n, c, s])
/content/stable-audio-tools/stable_audio_tools/models/blocks.py:68: UserWarning: Flash attention kernel not used because: (Triggered internally at ../aten/src/ATen/native/transformers/cuda/sdp_utils.cpp:417.)
  y = F.scaled_dot_product_attention(q, k, v, is_causal=False).contiguous().view([n, c, s])
/content/stable-audio-tools/stable_audio_tools/models/blocks.py:68: UserWarning: Both fused kernels require the last dimension of the input to have stride 1. Got Query.stride(-1): 256, Key.stride(-1): 256, Value.stride(-1): 256 instead. (Triggered internally at ../aten/src/ATen/native/transformers/sdp_utils_cpp.h:423.)
  y = F.scaled_dot_product_attention(q, k, v, is_causal=False).contiguous().view([n, c, s])
RuntimeError: No available kernel. Aborting execution.
```

Any clues on how to solve this?

**Comment by dctian** [comment]
Hi there, I am also trying to set up the training in colab. but after i did pip install, and try to create a model, I get an import error related to protobuf.   Would you please share a link to your colab?  thanks so much!

Here is my model initialization code: 
```
import stable_audio_tools as sa
import json

model_config_str = '/content/stable-audio-tools/stable_audio_tools/configs/model_configs/txt2audio/stable_audio_1_0.json'
with open(model_config_str, 'r') as f:
  model_config = json.load(f)

sa.models.factory.create_model_from_config(model_config)
```

I get this import error:
```
/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:311: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py in _get_module(self, module_name)
   1183         try:
-> 1184             return importlib.import_module("." + module_name, self.__name__)
   1185         except Exception as e:

45 frames
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (/usr/local/lib/python3.10/dist-packages/google/protobuf/internal/__init__.py)

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
RuntimeError: Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
cannot import name 'builder' from 'google.protobuf.internal' (/usr/local/lib/python3.10/dist-packages/google/protobuf/internal/__init__.py)

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py in _get_module(self, module_name)
   1184             return importlib.import_module("." + module_name, self.__name__)
   1185         except Exception as e:
-> 1186             raise RuntimeError(
   1187                 f"Failed to import {self.__name__}.{module_name} because of the following error (look up to see its"
   1188                 f" traceback):\n{e}"

RuntimeError: Failed to import transformers.models.bert.modeling_bert because of the following error (look up to see its traceback):
Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
cannot import name 'builder' from 'google.protobuf.internal' (/usr/local/lib/python3.10/dist-packages/google/protobuf/internal/__init__.py)
```

**Comment by fred-dev** [comment]
To make this easier to manage in Colab, use miniconda to create a virtual environment with the correct python version (the repo works fine with 3.8.10 and 3.9.2 for me - I have not tested further) and run your install and the code inside the virtual environment. This will help avoid these kinds of errors, often related to a version miss-match between libraries that are pre-installed in the colab environment (or the python version in the colab environment) and the specific version requirements of the code you are using.

This means you do need to setup the venv each time you run the colab notebook, and run the install process (which you would need to do anyway as Colab is not persistent). It will mitigate the errors you are facing.

**Comment by fmiotello** [comment]
Hi @fred-dev, did you find out what was causing this problem? I'm facing it too

**Comment by fred-dev** [comment]
> Hi @fred-dev, did you find out what was causing this problem? I'm facing it too

If you use miniconda as mentioned above it will work fine.

**Comment by Taikakim** [comment]
Just a note, that for me training in Colab with an A100 works without a problem, except the complaint about Flash Attention and the request to set torch.set_float32_matmul_precision('medium|high')
